// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVaUQ67YIEJSGHvitJ53HtF5SKLd_IuKA',
    appId: '1:425450003183:android:ce923d6bbb487bc0',
    messagingSenderId: '425450003183',
    projectId: 'timecalendar-samuelprak',
    databaseURL: 'https://timecalendar-samuelprak.firebaseio.com',
    storageBucket: 'timecalendar-samuelprak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCruJHHXWmT_lPib__T8iHOK8z05JdsEMY',
    appId: '1:425450003183:ios:ce923d6bbb487bc0',
    messagingSenderId: '425450003183',
    projectId: 'timecalendar-samuelprak',
    databaseURL: 'https://timecalendar-samuelprak.firebaseio.com',
    storageBucket: 'timecalendar-samuelprak.appspot.com',
    androidClientId:
        '425450003183-2bjqj66dbq23tngncts04i4l9mq7jrvp.apps.googleusercontent.com',
    iosClientId:
        '425450003183-1elevc6cg39idiukk9lh5sjtufis8h0r.apps.googleusercontent.com',
    iosBundleId: 'fr.samuelprak.timecalendar',
  );
}
