kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "timecalendar.fullname" . }}-configmap
data:
  # Node
  NODE_ENV: "production"

  # HTTP
  PORT: "80"

  # URLs
  CLIENT_URL: "https://{{ .Values.clientUrl }}"

  # Redis
  REDIS_QUEUE: timecalendar
  REDIS_URL: rediss://{{ .Values.timecalendar.redis.username }}:{{ .Values.timecalendar.redis.password }}@{{ .Values.timecalendar.redis.host }}:{{ .Values.timecalendar.redis.port }}
  REDIS_KEY_PREFIX: {{ .Values.environment }}

  # Postgres
  DATABASE_HOST: {{ .Values.timecalendar.database.host }}
  DATABASE_PORT: "{{ .Values.timecalendar.database.port }}"
  DATABASE_USERNAME: {{ .Values.timecalendar.database.username }}
  DATABASE_PASSWORD: {{ .Values.timecalendar.database.password }}
  DATABASE_MAIN_NAME: {{ .Values.timecalendar.database.database }}
  PGSSLMODE: no-verify

  RUN_MIGRATIONS: "true"

  # SMTP
  SMTP_FROM: {{ .Values.timecalendar.smtpFrom }}
  SMTP_URL: {{ .Values.timecalendar.smtpUrl }}

  API_USERNAME: {{ .Values.timecalendar.apiUsername }}
  API_TOKEN: {{ .Values.timecalendar.apiToken }}

  S3_PUBLIC_BUCKET_CLIENT_URL: {{ .Values.timecalendar.s3PublicBucketClientUrl }}

  CRISP_IDENTIFIER: {{ .Values.timecalendar.crisp.identifier }}
  CRISP_KEY: {{ .Values.timecalendar.crisp.key }}
  CRISP_WEBSITE_ID: {{ .Values.timecalendar.crisp.websiteId }}
