apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "timecalendar.fullname" . }}
  labels:
    {{- include "timecalendar.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "timecalendar.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "timecalendar.selectorLabels" . | nindent 8 }}
    spec:
      # {{- with .Values.imagePullSecrets }}
      # imagePullSecrets:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "ghcr.io/timecalendar/timecalendar:{{ .Values.server.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "768Mi"
              cpu: "1000m"
            limits:
              memory: "768Mi"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 4
            periodSeconds: 30
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 120
            periodSeconds: 2
          envFrom:
            - configMapRef:
                name: {{ include "timecalendar.fullname" . }}-configmap
          volumeMounts:
            - mountPath: /usr/src/app/config
              name: config-volume
      volumes:
        - name: config-volume
          secret:
            secretName: timecalendar-secret
