apiVersion: v1
kind: Service
metadata:
  name: {{ include "timecalendar.fullname" . }}-web
  labels:
    {{- include "timecalendar.webLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    {{- include "timecalendar.webSelectorLabels" . | nindent 4 }}
