source "https://rubygems.org"

gem "fastlane"
gem "fastlane-plugin-flutter_version", git: "https://github.com/tianhaoz95/fastlane-plugin-flutter-version"
gem "fastlane-plugin-firebase_app_distribution"
gem "fastlane-plugin-get_new_build_number"
