analyzer:
  errors:
    # allow self-reference to deprecated members (we do this because otherwise we have
    # to annotate every member in every test, assert, etc, when we deprecate something)
    deprecated_member_use_from_same_package: ignore
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    - always_use_package_imports
    - avoid_relative_lib_imports