name: timecalendar
description: Votre emploi du temps universitaire
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+15

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  build_runner: ^2.1.7
  built_collection: ^5.1.1
  built_value: ^8.4.1
  built_value_generator: ^8.4.1
  color: ^3.0.0
  cupertino_icons: ^1.0.4
  diacritic: ^0.1.3
  dio: ^4.0.4
  enum_to_string: ^2.0.1
  firebase_analytics: ^10.4.4
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5+1
  flutter_image: ^4.1.0
  flutter_local_notifications: ^15.1.0+1
  flutter_localizations:
    sdk: flutter
  flutter_material_color_picker: ^1.1.0+2
  flutter_sticky_header: ^0.6.0
  font_awesome_flutter: ^10.5.0
  freezed: ^2.1.0+1
  google_sign_in: ^6.1.4
  hooks_riverpod: ^2.3.6
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  package_info_plus: ^4.0.2
  path_provider: ^2.0.8
  permission_handler: ^10.4.3
  pref: ^2.5.0
  provider: ^6.0.2
  qr_code_scanner: ^1.0.0
  reorderables: ^0.6.0
  scrollable_positioned_list: ^0.3.2
  sembast: ^3.1.2
  shared_preferences: ^2.0.12
  state_notifier: ^0.7.2+1
  timecalendar_api:
    path: ../openapi/dart
  tuple: ^2.0.0
  url_launcher: ^6.0.18
  uuid: ^3.0.5
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/home.png
    - assets/images/notifications.png
    - assets/images/schools.png
    - .env
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.otf
          weight: 100
        - asset: assets/fonts/Poppins-Thin.otf
          weight: 200
        - asset: assets/fonts/Poppins-Light.otf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.otf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Poppins-Black.otf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-assets/fonts/#from-packages
