volumes:
  postgres:
  redis:

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - '1443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../ci/certificates:/etc/nginx/certificates
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5433:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./bin/init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis
    restart: always
    ports:
      - '6370:6379'
    volumes: 
      - redis:/data
