services:
  nginx:
    image: nginx
    restart: always
    ports:
      - '1443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../ci/certificates:/etc/nginx/certificates
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '37291:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bin/init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready -U postgres"]
  redis:
    image: redis
    restart: always
    ports:
      - '37292:6379'
    volumes: 
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
