# Default values for timecalendar.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: ""

server:
  replicaCount: 1
  tag: ""
web:
  replicaCount: 1
  tag: ""

nameOverride: ""
fullnameOverride: ""

# TimeCalendar custom values
apiUrl: ""
clientUrl: ""
webUrl: ""

timecalendar:
  database:
    host: ""
    port: ""
    username: ""
    database: ""
    password: ""
  apiUsername: ""
  apiToken: ""
  smtpUrl: ""
  smtpFrom: ""
  s3PublicBucketClientUrl: ""
  otel:
    enabled: ""
    exporterUrl: ""
