environment: preprod
apiUrl: preprod-api.timecalendar.app
clientUrl: preprod.timecalendar.app
webUrl: preprod-web.timecalendar.app

server:
  replicaCount: 1

web:
  replicaCount: 1

timecalendar:
  s3PublicBucketClientUrl: https://timecalendar-preprod-public.fra1.digitaloceanspaces.com
