apiUrl: "preprod-api.timecalendar.app"
clientUrl: "preprod.timecalendar.app"
webUrl: "preprod-web.timecalendar.app"

server:
  replicaCount: 1
  image:
    tag: latest

web:
  replicaCount: 1
  image:
    tag: latest
