#!/bin/bash

if [[ $GITHUB_REF == 'refs/heads/production' ]]; then
  TARGET_ENVIRONMENT=production
  DOCKER_TAG=production
else
  TARGET_ENVIRONMENT=preprod
  DOCKER_TAG=latest
fi

echo "TARGET_ENVIRONMENT=$TARGET_ENVIRONMENT" >> "$GITHUB_ENV"
echo "DOCKER_TAG=$DOCKER_TAG" >> "$GITHUB_ENV"
echo "K8S_KUBECONFIG_ENV=K8S_KUBECONFIG_${TARGET_ENVIRONMENT^^}" >> "$GITHUB_ENV"
echo "K8S_HELM_VALUES_ENV=K8S_HELM_VALUES_${TARGET_ENVIRONMENT^^}" >> "$GITHUB_ENV"
