#!/bin/bash

if [[ $GITHUB_REF == 'refs/heads/production' ]]; then
  TARGET_ENVIRONMENT=production
  MAIN_DOCKER_TAG=production
elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
  TARGET_ENVIRONMENT=preprod
  MAIN_DOCKER_TAG=latest
fi

echo "TARGET_ENVIRONMENT=$TARGET_ENVIRONMENT"
echo "MAIN_DOCKER_TAG=$MAIN_DOCKER_TAG"

export SERVER_IMAGE_NAME=ghcr.io/timecalendar/timecalendar
export WEB_IMAGE_NAME=ghcr.io/timecalendar/timecalendar-web

export SERVER_IMAGE_NAME_WITH_TAG=$SERVER_IMAGE_NAME:$GITHUB_SHA
export WEB_IMAGE_NAME_WITH_TAG=$WEB_IMAGE_NAME:$GITHUB_SHA

export SERVER_IMAGES_WITH_TAG_TO_PUSH=$SERVER_IMAGE_NAME_WITH_TAG
if [ -n "$MAIN_DOCKER_TAG" ]; then
  SERVER_IMAGES_WITH_TAG_TO_PUSH+=", $WEB_IMAGE_NAME:$MAIN_DOCKER_TAG"
fi
export WEB_IMAGES_WITH_TAG_TO_PUSH=$WEB_IMAGE_NAME_WITH_TAG
if [ -n "$MAIN_DOCKER_TAG" ]; then
  WEB_IMAGES_WITH_TAG_TO_PUSH+=", $WEB_IMAGE_NAME:$MAIN_DOCKER_TAG"
fi


echo "[server] Tags to push: $SERVER_IMAGES_WITH_TAG_TO_PUSH"
echo "[web] Tags to push: $WEB_IMAGES_WITH_TAG_TO_PUSH"

echo "SERVER_IMAGES_WITH_TAG_TO_PUSH=$SERVER_IMAGES_WITH_TAG_TO_PUSH" >> "$GITHUB_ENV"
echo "WEB_IMAGES_WITH_TAG_TO_PUSH=$WEB_IMAGES_WITH_TAG_TO_PUSH" >> "$GITHUB_ENV"

echo "MAIN_DOCKER_TAG=$MAIN_DOCKER_TAG" >>"$GITHUB_ENV"
echo "DOCKER_TAG=$GITHUB_SHA" >>"$GITHUB_ENV"

# K8s deployment
if [ -n "$TARGET_ENVIRONMENT" ]; then
  echo "TARGET_ENVIRONMENT=$TARGET_ENVIRONMENT" >>"$GITHUB_ENV"
  echo "K8S_KUBECONFIG_ENV=K8S_KUBECONFIG_${TARGET_ENVIRONMENT^^}" >>"$GITHUB_ENV"
  echo "K8S_HELM_VALUES_ENV=K8S_HELM_VALUES_${TARGET_ENVIRONMENT^^}" >>"$GITHUB_ENV"
fi
