environment: production
apiUrl: api-v2.timecalendar.app
clientUrl: timecalendar.app
webUrl: v2.timecalendar.app

server:
  replicaCount: 3

web:
  replicaCount: 1

timecalendar:
  s3PublicBucketClientUrl: https://timecalendar-public.fra1.digitaloceanspaces.com
  otel:
    enabled: "true"
    exporterUrl: "http://otelcol-dev-collector.lyro-opentelemetry.svc.cluster.local:4317"
