name: CI build

on: push

jobs:
  build-server:
    name: Build server image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/timecalendar/timecalendar
    steps:

    - name: Checkout main
      uses: actions/checkout@v2

    - name: Set target environment
      run: ./ci/set-target-env.sh

    - name: Load Docker Layer Caching
      uses: satackey/action-docker-layer-caching@v0.0.11
      with:
        key: build-server-docker-cache-{hash}
        restore-keys: |
          build-server-docker-cache-
      continue-on-error: true

    - name: Build container image
      working-directory: ./server
      run: docker build -t $IMAGE_NAME:${{ github.sha }} .

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image to GitHub Container Registry
      run: docker push $IMAGE_NAME:${{ github.sha }}

    - name: Push deployable version
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production'
      run: |
        docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:${{ env.DOCKER_TAG }}
        docker push $IMAGE_NAME:${{ env.DOCKER_TAG }}


  build-web:
    name: Build web image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/timecalendar/timecalendar-web
    steps:

    - name: Checkout main
      uses: actions/checkout@v2

    - name: Set target environment
      run: ./ci/set-target-env.sh

    - name: Load Docker Layer Caching
      uses: satackey/action-docker-layer-caching@v0.0.11
      with:
        key: build-web-docker-cache-{hash}
        restore-keys: |
          build-web-docker-cache-
      continue-on-error: true

    - name: Build container image
      run: docker build -t $IMAGE_NAME:${{ github.sha }} -f Dockerfile.web .

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image to GitHub Container Registry
      run: docker push $IMAGE_NAME:${{ github.sha }}

    - name: Push deployable version
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production'
      run: |
        docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:${{ env.DOCKER_TAG }}
        docker push $IMAGE_NAME:${{ env.DOCKER_TAG }}

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build-server
    steps:

    - name: Checkout main
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Start Postgres and Redis
      run: docker-compose --env-file ./ci/.env.test -f server/docker-compose.yml --profile ci up -d postgres redis

    - name: Wait for Postgres and Redis
      run: |
        ./ci/wait.sh -h localhost -p 5433 -t 60
        ./ci/wait.sh -h localhost -p 6370 -t 60

    - name: Run tests
      run: docker run --env-file="./ci/.env.test" -e CI=true --network host ghcr.io/timecalendar/timecalendar:${{ github.sha }} npm run test


  # deploy:
  #   name: Deploy on environment
  #   needs: build
  #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production'
  #   runs-on: ubuntu-latest
  #   steps:

  #   - name: Checkout main
  #     uses: actions/checkout@v2

  #   - name: Set target environment
  #     run: ./ci/set-target-env.sh

  #   - name: Set target environment Helm values
  #     run: echo "${{ secrets[env.K8S_HELM_VALUES_ENV] }}" > ./k8s/environments/$TARGET_ENVIRONMENT/secret-values.yaml

  #   - name: Set Kubernetes context
  #     uses: azure/k8s-set-context@v2
  #     with:
  #       method: kubeconfig
  #       kubeconfig: ${{ secrets[env.K8S_KUBECONFIG_ENV] }}

  #   - name: Deploy
  #     run: ./k8s/deploy.sh
