name: CI test and build

on: push

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@v2

    - name: Load Docker Layer Caching
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: Set environment for branch
      run: |
        if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "DOCKER_TAG=production" >> "$GITHUB_ENV"
        else
            echo "DOCKER_TAG=latest" >> "$GITHUB_ENV"
        fi

    - name: Build container image
      run: docker build -t ghcr.io/timecalendar/timecalendar:${{ env.DOCKER_TAG }} .

    - name: Start MySQL
      run: docker-compose --env-file ./ci/.env.test --profile ci up mysql_test -d

    - name: Wait for MySQL
      run: ./ci/wait.sh -h localhost -p 3308 -t 60

    - name: Run tests
      run: docker run --env-file="./ci/.env.test" -e CI=true --network host ghcr.io/timecalendar/timecalendar:${{ env.DOCKER_TAG }} yarn test

    - name: Log in to GitHub Container Registry
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image to GitHub Container Registry
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      run: docker push ghcr.io/timecalendar/timecalendar:${{ env.DOCKER_TAG }}
